version: '3.8'

services:
  auth-service:
    build:
      context: .
      dockerfile: auth/Dockerfile
    environment:
      - DATABASE_URL=mysql+pymysql://root:987654321@db:3306/ecommerce
      - PYTHONPATH=/app:/app/shared
    ports:
      - "3004:3004"
    depends_on:
      db:
        condition: service_healthy

  customer-service:
    build:
      context: .
      dockerfile: customers/Dockerfile
    environment:
      - DATABASE_URL=mysql+pymysql://root:987654321@db:3306/ecommerce
      - PYTHONPATH=/app:/app/shared
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  sales-service:
    build:
      context: .
      dockerfile: sales/Dockerfile
    environment:
      - DATABASE_URL=mysql+pymysql://root:987654321@db:3306/ecommerce
      - PYTHONPATH=/app:/app/shared
    ports:
      - "3003:3003"
    depends_on:
      db:
        condition: service_healthy

  review-service:
    build:
      context: .
      dockerfile: reviews/Dockerfile
    environment:
      - DATABASE_URL=mysql+pymysql://root:987654321@db:3306/ecommerce
      - PYTHONPATH=/app:/app/shared
    ports:
      - "3002:3002"
    depends_on:
      db:
        condition: service_healthy

  inventory-service:
    build:
      context: .
      dockerfile: inventory/Dockerfile
    environment:
      - DATABASE_URL=mysql+pymysql://root:987654321@db:3306/ecommerce
      - PYTHONPATH=/app:/app/shared
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 987654321
      MYSQL_DATABASE: ecommerce
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p987654321"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
